spring.application.name=missionplan

server.port=9080
server.servlet.session.tracking-modes=cookie

spring.datasource.url=${DB_URL}
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.maximum-pool-size=3

spring.jpa.hibernate.ddl-auto=update
